import puppeteer from 'puppeteer-core'
import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'


const origin=process.env.NAV_TEST_ORIGIN || 'http://127.0.0.1:5174'
const fixture=await readFile(new URL('../../wireforge-backend/target/navigation-runtime-fixture.html',import.meta.url),'utf8')
const browser=await puppeteer.launch({executablePath:process.env.NAV_TEST_BROWSER || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',userDataDir:process.env.NAV_TEST_PROFILE || undefined,headless:true,args:['--no-sandbox','--disable-gpu']})
try {
  const page=await browser.newPage();await page.setViewport({width:1400,height:1000})
  const errors=[];page.on('pageerror',e=>errors.push(String(e)))
  await page.setRequestInterception(true)
  page.on('request',request=> {
    const url=new URL(request.url())
    if(url.pathname==='/__navigation_fixture')return request.respond({status:200,contentType:'text/html; charset=utf-8',body:fixture})
    if(url.pathname.startsWith('/api/') || (url.protocol.startsWith('http') && url.origin!==origin))return request.abort()
    request.continue()
  })
  await page.goto(origin+'/tests/navigation-harness.html');await page.waitForSelector('iframe.html-frame')
  const handle=await page.$('iframe.html-frame');const frame=await handle.contentFrame()
  await frame.waitForSelector('[data-wf-nav-owner="10"]')
  const count=()=>page.evaluate(()=>window.navTest.navigations.length)
  for(const selector of ['.nav-item svg','.nav-item span']) {
    const before=await count();await frame.click(selector);await page.waitForFunction(n=>window.navTest.navigations.length>n,{},before)
    assert.equal(await count(),before+1,'Each icon/text click dispatches once')
  }
  const wrapper=await frame.$('.nav-item'),rect=await wrapper.boundingBox();const before=await count()
  await page.mouse.click(rect.x+7,rect.y+rect.height-7);await page.waitForFunction(n=>window.navTest.navigations.length>n,{},before)
  assert.equal(await count(),before+1,'Wrapper empty space responds')
  const area=await frame.$('.wf-nav-hotspot');assert.ok(area,'Flat navigation has a presentation hotspot')
  const beforeFlat=await count();await area.click();await page.waitForFunction(n=>window.navTest.navigations.length>n,{},beforeFlat)
  assert.equal(await page.evaluate(()=>window.navTest.navigations.at(-1)),'我的')
  assert.equal(await frame.$('[data-wf-nav-owner="30"]'),null,'Independent child action must not be covered')
  assert.equal(await frame.$eval('[data-wf-element-id="99"]',n=>n.getAttribute('data-action')),'toggle')
  await page.evaluate(()=>window.navTest.edit());await frame.waitForFunction(()=>!document.body.classList.contains('wf-interactive'))
  assert.equal(await frame.$eval('.wf-nav-hotspot',n=>getComputedStyle(n).display),'none','Hotspots stay out of editing')
  assert.equal(await frame.$eval('[data-wf-element-id="21"]',n=>n.textContent),'我的','Member element identity stays intact')
  await frame.evaluate(()=> {
    document.querySelector('[data-wf-element-id="11"]').setAttribute('data-nav','我的')
    const node=document.getElementById('wf-autowire-bindings'),rows=JSON.parse(node.textContent)
    rows.find(b=>b.elementId===10).action='none';node.textContent=JSON.stringify(rows)
    const script=Array.from(document.scripts).find(s=>s.textContent.includes("var rows=JSON.parse(document.getElementById('wf-autowire-bindings')"))
    window.eval(script.textContent)
  })
  assert.equal(await frame.$eval('.nav-item',n=>n.getAttribute('data-nav')),null,'Deleted owner loses navigation')
  assert.equal(await frame.$eval('[data-wf-element-id="11"]',n=>n.getAttribute('data-nav')),'我的','Deleting one binding preserves surviving member action')
  const row=id=>'.relation-row[data-item-id="'+id+'"]'
  const check=id=>row(id)+' > input[type=checkbox]'
  const target='select[aria-label="跳转目标 首页 · 我的"]'
  const apply=()=>page.click('.actions .el-button--primary')
  const last=()=>page.evaluate(()=>window.navTest.applied.at(-1))
  const activate=async id=>{await page.click(row(id));await page.waitForFunction(value=>document.querySelector('.relation-detail')?.getAttribute('data-active-item-id')===value,{},id)}
  const checkStates=()=>page.$$eval('.relation-row > input[type=checkbox]',nodes=>nodes.map(node=>node.checked))
  const route=()=>page.$eval('.relation-detail',node=>({source:node.querySelector('.source-card header strong').textContent,control:node.querySelector('.detail-heading h3').textContent,target:node.querySelector('.target-card select')?.selectedOptions[0]?.textContent||node.querySelector('.target-card header strong')?.textContent}))
  const search=async value=>{await page.$eval('input[aria-label="搜索页面或控件"]',(node,text)=>{node.value=text;node.dispatchEvent(new Event('input',{bubbles:true}))},value)}
  await page.evaluate(()=>window.navTest.open());await page.waitForSelector('.autowire-dialog')
  assert.deepEqual(await route(),{source:'首页',control:'我的',target:'我的'},'Source page, clicked control and destination are explicit')
  assert.match(await page.$eval('.relation-sentence',node=>node.textContent),/在「首页」点击「我的」，跳转到「我的」/)
  assert.equal(await page.$eval('.item-more',node=>node.open),false,'Optional controls start collapsed')
  assert.equal(await page.$eval(target,node=>node.getBoundingClientRect().height>0&&!node.disabled),true)
  assert.deepEqual(await checkStates(),[true,true])
  await page.click(check('unchecked'));await page.evaluate(()=>window.navTest.unchanged())
  await page.waitForFunction(()=>document.querySelectorAll('.relation-row').length===2)
  assert.deepEqual(await checkStates(),[true,false],'Checked and unchecked decisions survive an unchanged preview')
  await activate('checked');await page.select(target,'3')
  assert.deepEqual(await checkStates(),[true,false],'Choosing a destination immediately checks this relation only')
  assert.equal(await page.$eval('.actions .el-button--primary',node=>node.disabled),false,'A chosen target can be applied directly')
  assert.match(await page.$eval('.relation-sentence',node=>node.textContent),/跳转到「设置」/)
  assert.equal(await page.$$eval('.actions button',nodes=>nodes.some(node=>/检查新目标|重新检查/.test(node.textContent))),false,'Normal review has no separate verification button')
  await apply()
  assert.deepEqual((await last()).selectedIds,['checked'])
  assert.deepEqual((await last()).navigationResolutions,[{stableKey:'1:nav:family:checked',targetPageId:3}])
  assert.deepEqual((await last()).targetResolutions,[])
  assert.equal(await page.evaluate(()=>window.navTest.requests.length),0,'Changing and applying a target never triggers the recompute event')
  await page.click('.item-more > summary')
  await page.select('select[aria-label="下次还推荐吗 首页 · 我的"]','relation')
  assert.equal(await page.$eval(target,node=>node.value),'2','Excluding a proposal restores its original target rather than showing an unsaved choice')
  assert.match(await page.$eval('.sentence-label',node=>node.textContent),/以后不再推荐的关系/)
  await apply()
  assert.deepEqual((await last()).exclusions,[{itemId:'checked',scope:'relation'}])
  assert.deepEqual((await last()).navigationResolutions,[])

  await page.evaluate(()=>window.navTest.sampleReview());await page.waitForSelector(row('exchange'))
  await activate('exchange')
  assert.deepEqual(await route(),{source:'限时兑换商店',control:'兑换记录',target:'兑换记录'})
  assert.match(await page.$eval('.previous-relation',node=>node.textContent),/只切换本页内容/,'Old local action is expressed separately')
  assert.match(await page.$eval('.change-tag',node=>node.textContent),/改为页面跳转/)
  await activate('account')
  assert.match(await page.$eval('.previous-relation',node=>node.textContent),/跳转「设置」/,'Old destination uses its actual page name')
  await activate('exchange');await page.click(check('exchange'))
  await search('首页');await page.waitForFunction(()=>document.querySelectorAll('.relation-row').length===1)
  assert.equal(await page.$eval('.source-card header strong',node=>node.textContent),'首页')
  assert.match(await page.$eval('.footer',node=>node.textContent),/已选 1 条关系/)
  assert.match(await page.$eval('.footer',node=>node.textContent),/1 条在当前筛选外/,'Pending choices outside the current filter remain explicit')
  await apply();assert.deepEqual((await last()).selectedIds,['exchange'],'Search does not discard a selection outside the visible results')
  await search('');await page.waitForFunction(()=>document.querySelectorAll('.relation-row').length===2)
  assert.equal(await page.$eval(check('exchange'),node=>node.checked),true)
  await activate('exchange');await page.click('.item-more > summary')
  const preference='select[aria-label="下次还推荐吗 限时兑换商店 · 兑换记录"]'
  assert.deepEqual(await page.$$eval(preference+' option',nodes=>nodes.map(node=>node.textContent)),['继续推荐','以后不再推荐这条跳转','以后不再推荐此控件的关系'])
  await page.select(preference,'relation')
  assert.equal(await page.$eval(check('exchange'),node=>node.checked),false,'Excluding a recommendation removes its apply selection')
  await apply();assert.deepEqual((await last()).exclusions,[{itemId:'exchange',scope:'relation'}])
  await page.select(preference,'element');await apply();assert.deepEqual((await last()).exclusions,[{itemId:'exchange',scope:'element'}])
  await page.select(preference,'')
  await page.evaluate(()=>window.navTest.restoreReview())
  await page.$$eval('.review-tabs button',nodes=>nodes.find(node=>node.textContent.includes('不再推荐')).click())
  await page.waitForSelector('.exclusion-row input')
  await page.click('.exclusion-row input');await apply()
  assert.deepEqual((await last()).restoreExclusionIds,[88],'Restoring recommendations is applied explicitly')

  await page.evaluate(()=>window.navTest.unresolvedReview())
  await page.$$eval('.review-tabs button',nodes=>nodes.find(node=>node.textContent.includes('设置关系')).click())
  await page.waitForSelector(row('unresolved'))
  assert.equal(await page.$eval(check('unresolved'),node=>node.disabled),true,'A missing destination remains unselectable')
  assert.match(await page.$eval('.needs-attention',node=>node.textContent),/选择右侧的跳转页面/)
  await page.select(target,'2')
  assert.equal(await page.$eval(check('unresolved'),node=>!node.disabled&&node.checked),true,'Choosing an allowed navigation destination immediately selects the relation')
  await apply()
  assert.deepEqual((await last()).selectedIds,['unresolved'])
  assert.deepEqual((await last()).navigationResolutions,[{stableKey:'1:unresolved',targetPageId:2}])
  assert.deepEqual((await last()).targetResolutions,[])
  await page.select(target,'')
  assert.equal(await page.$eval(check('unresolved'),node=>node.checked),false,'Clearing the destination also clears selection')

  await page.evaluate(()=>window.navTest.ordinaryUnresolvedReview());await page.waitForSelector(row('ordinary'))
  await page.select(target,'2')
  assert.equal(await page.$eval(check('ordinary'),node=>!node.disabled&&node.checked),true)
  await apply()
  assert.deepEqual((await last()).selectedIds,['ordinary'])
  assert.deepEqual((await last()).targetResolutions,[{stableKey:'1:ordinary',targetPageId:2}])
  assert.deepEqual((await last()).navigationResolutions,[])
  await page.select(target,'3');await page.click('.item-more > summary')
  await page.select('select[aria-label="下次还推荐吗 首页 · 我的"]','element');await apply()
  assert.deepEqual((await last()).exclusions,[{itemId:'ordinary',scope:'element'}])
  assert.deepEqual((await last()).selectedIds,[])
  assert.deepEqual((await last()).targetResolutions,[],'Exclusions do not submit unrelated pending destination choices')

  await page.evaluate(()=>window.navTest.ordinaryExistingReview());await page.waitForSelector(row('original-account'))
  assert.match(await page.$eval('.previous-relation',node=>node.textContent),/跳转「设置」/)
  await page.evaluate(()=>window.navTest.refreshExistingRelation(2))
  assert.match(await page.$eval('.previous-relation',node=>node.textContent),/跳转「设置」/,'Refreshing a saved target cannot rewrite the original relationship in the comparison')
  await page.evaluate(()=>window.navTest.refreshExistingRelation(null))
  assert.match(await page.$eval('.previous-relation',node=>node.textContent),/跳转「设置」/,'Deleting the saved line cannot erase its before-state from this review')
  await page.evaluate(()=>window.navTest.existingTargetsReview());await page.waitForSelector(row('existing-account'))
  assert.deepEqual(await page.$$eval('.relation-row > input[type=checkbox]',nodes=>nodes.map(node=>node.disabled)),[false,false],'Existing allowed destinations can be confirmed without choosing again')
  assert.deepEqual(await checkStates(),[false,false])
  await page.click(check('existing-account'));await page.click(check('existing-settings'))
  assert.deepEqual(await checkStates(),[true,true])
  assert.equal(await page.$eval('.actions .el-button--primary',node=>node.disabled),false,'Batch confirmations can be applied immediately')
  await apply()
  assert.deepEqual((await last()).selectedIds,['existing-account','existing-settings'])
  assert.deepEqual((await last()).targetResolutions,[{stableKey:'1:existing-account',targetPageId:2},{stableKey:'1:existing-settings',targetPageId:3}])
  assert.equal(await page.evaluate(()=>window.navTest.requests.length),0,'No checkbox, destination or apply action invokes another AI preview')
  await page.evaluate(()=>window.navTest.conflictReview());await page.waitForSelector(row('conflict'))
  assert.equal(await page.$('.relation-detail .target-picker select'),null,'Conflicts cannot be overwritten by choosing another destination')
  assert.equal(await page.$eval(check('conflict'),node=>node.disabled),true,'Conflicting relations remain protected')
  assert.match(await page.$eval('.needs-attention',node=>node.textContent),/现有关系有冲突/)
  assert.deepEqual(errors,[])
  console.log('PASS: iframe navigation; page comparison clarity; direct navigation/ordinary destination application; existing-target batch confirmations; search and selection memory; recommendation exclusions/restores; conflict protection; no repeated AI preview or API writes.')
} finally {await browser.close()}
