import puppeteer from 'puppeteer-core'
import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'
import { fileURLToPath } from 'node:url'

const origin=process.env.NAV_TEST_ORIGIN || 'http://127.0.0.1:5174'
const fixture=await readFile(new URL('../../wireforge-backend/target/navigation-runtime-fixture.html',import.meta.url),'utf8')
const browser=await puppeteer.launch({executablePath:process.env.NAV_TEST_BROWSER || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',userDataDir:process.env.NAV_TEST_PROFILE || undefined,headless:true,args:['--no-sandbox','--disable-gpu']})
try {
  const page=await browser.newPage();await page.setViewport({width:1400,height:1000})
  const errors=[];page.on('pageerror',e=>errors.push(String(e)))
  await page.setRequestInterception(true)
  page.on('request',request=> {
    const url=new URL(request.url())
    if(url.pathname==='/__navigation_fixture')return request.respond({status:200,contentType:'text/html; charset=utf-8',body:fixture})
    if(url.pathname.startsWith('/api/') || (url.protocol.startsWith('http') && url.origin!==origin))return request.abort()
    request.continue()
  })
  await page.goto(origin+'/tests/navigation-harness.html');await page.waitForSelector('iframe.html-frame')
  const handle=await page.$('iframe.html-frame');const frame=await handle.contentFrame()
  await frame.waitForSelector('[data-wf-nav-owner="10"]')
  const count=()=>page.evaluate(()=>window.navTest.navigations.length)
  for(const selector of ['.nav-item svg','.nav-item span']) {
    const before=await count();await frame.click(selector);await page.waitForFunction(n=>window.navTest.navigations.length>n,{},before)
    assert.equal(await count(),before+1,'Each icon/text click dispatches once')
  }
  const wrapper=await frame.$('.nav-item'),rect=await wrapper.boundingBox();const before=await count()
  await page.mouse.click(rect.x+7,rect.y+rect.height-7);await page.waitForFunction(n=>window.navTest.navigations.length>n,{},before)
  assert.equal(await count(),before+1,'Wrapper empty space responds')
  const area=await frame.$('.wf-nav-hotspot');assert.ok(area,'Flat navigation has a presentation hotspot')
  const beforeFlat=await count();await area.click();await page.waitForFunction(n=>window.navTest.navigations.length>n,{},beforeFlat)
  assert.equal(await page.evaluate(()=>window.navTest.navigations.at(-1)),'我的')
  assert.equal(await frame.$('[data-wf-nav-owner="30"]'),null,'Independent child action must not be covered')
  assert.equal(await frame.$eval('[data-wf-element-id="99"]',n=>n.getAttribute('data-action')),'toggle')
  await page.evaluate(()=>window.navTest.edit());await frame.waitForFunction(()=>!document.body.classList.contains('wf-interactive'))
  assert.equal(await frame.$eval('.wf-nav-hotspot',n=>getComputedStyle(n).display),'none','Hotspots stay out of editing')
  assert.equal(await frame.$eval('[data-wf-element-id="21"]',n=>n.textContent),'我的','Member element identity stays intact')
  await frame.evaluate(()=> {
    document.querySelector('[data-wf-element-id="11"]').setAttribute('data-nav','我的')
    const node=document.getElementById('wf-autowire-bindings'),rows=JSON.parse(node.textContent)
    rows.find(b=>b.elementId===10).action='none';node.textContent=JSON.stringify(rows)
    const script=Array.from(document.scripts).find(s=>s.textContent.includes("var rows=JSON.parse(document.getElementById('wf-autowire-bindings')"))
    window.eval(script.textContent)
  })
  assert.equal(await frame.$eval('.nav-item',n=>n.getAttribute('data-nav')),null,'Deleted owner loses navigation')
  assert.equal(await frame.$eval('[data-wf-element-id="11"]',n=>n.getAttribute('data-nav')),'我的','Deleting one binding preserves surviving member action')
  await page.evaluate(()=>window.navTest.open());await page.waitForSelector('.autowire-dialog')
  const route=()=>page.$eval('article.item .relation-route',node=>Array.from(node.querySelectorAll('.route-point')).map(n=>n.querySelector('select')?.selectedOptions[0]?.textContent || n.querySelector('strong')?.textContent))
  assert.deepEqual(await route(),['首页','我的','我的'],'Source page, trigger element and target page are all explicit')
  assert.equal(await page.$eval('article.item .item-more',n=>n.open),false,'Optional controls start collapsed')
  assert.equal(await page.$eval('article.item .route-target select',n=>n.getBoundingClientRect().height>0 && !n.disabled),true,'Destination is a visible enabled selector')
  const checks=await page.$$('article.item input[type=checkbox]');assert.equal(checks.length,2)
  await checks[1].click();await page.evaluate(()=>window.navTest.unchanged())
  await page.waitForFunction(()=>document.querySelectorAll('article.item input[type=checkbox]').length===2)
  assert.deepEqual(await page.$$eval('article.item input[type=checkbox]',nodes=>nodes.map(n=>n.checked)),[true,false],'Unchecked choice survives recompute')
  await page.select('select[aria-label="跳转目标 首页 · 我的"]','3')
  assert.ok(await page.$eval('.actions .el-button--primary',n=>n.disabled),'Target change requires recomputation')
  await page.$$eval('.actions button',nodes=>nodes.find(n=>/重新检查|检查新目标/.test(n.textContent)).click())
  await page.waitForFunction(()=>window.navTest.requests.length===1)
  assert.deepEqual(await page.$$eval('article.item input[type=checkbox]',nodes=>nodes.map(n=>n.checked)),[false,false],'Changed target is unchecked; old unchecked stays unchecked')
  await (await page.$('article.item input[type=checkbox]')).click()
  await page.click('.actions .el-button--primary')
  assert.deepEqual(await page.evaluate(()=>window.navTest.applied[0].selectedIds),['checked'])
  assert.equal(await page.evaluate(()=>window.navTest.requests[0].navigationResolutions[0].targetPageId),3)
  await page.evaluate(()=>window.navTest.sampleReview())
  await page.waitForFunction(()=>document.querySelector('article.item .route-source strong')?.textContent==='限时兑换商店')
  assert.deepEqual(await route(),['限时兑换商店','兑换记录','兑换记录'])
  assert.match(await page.$eval('article.item .change-explanation',n=>n.textContent),/切换本页内容/)
  assert.match(await page.$$eval('.change-explanation',nodes=>nodes.map(n=>n.textContent).join('\n')),/跳转「设置」/,'Old target uses page name')
  await (await page.$('article.item input[type=checkbox]')).click()
  await page.select('select[aria-label="筛选来源页面"]','1')
  await page.waitForFunction(()=>document.querySelectorAll('article.item').length===1)
  assert.equal(await page.$eval('article.item .route-source strong',n=>n.textContent),'首页')
  assert.match(await page.$eval('.footer',n=>n.textContent),/1 条在当前筛选外/,'Filtering cannot conceal pending selections')
  await page.select('select[aria-label="筛选来源页面"]','')
  await page.waitForFunction(()=>document.querySelectorAll('article.item').length===2)
  assert.equal(await page.$eval('article.item input[type=checkbox]',n=>n.checked),true,'Filtering keeps review decisions')
  await page.click('article.item .item-more > summary')
  const preference='select[aria-label="下次还推荐吗 限时兑换商店 · 兑换记录"]'
  assert.deepEqual(await page.$$eval(preference+' option',nodes=>nodes.map(n=>n.textContent)),['继续推荐','别再推荐这个跳转','这个元素都不推荐'])
  await page.select(preference,'relation')
  assert.equal(await page.$eval('article.item input[type=checkbox]',n=>n.checked),false,'Stopping recommendations clears the apply selection')
  await page.click('.actions .el-button--primary')
  assert.deepEqual(await page.evaluate(()=>window.navTest.applied.at(-1).exclusions),[{itemId:'exchange',scope:'relation'}],'Plain language choice retains relation exclusion payload')
  await page.select(preference,'element');await page.click('.actions .el-button--primary')
  assert.deepEqual(await page.evaluate(()=>window.navTest.applied.at(-1).exclusions),[{itemId:'exchange',scope:'element'}],'Element-wide setting retains its existing scope')
  await page.select(preference,'')
  await page.evaluate(()=>window.navTest.unresolvedReview())
  await page.waitForSelector('.route-target.unresolved select')
  assert.equal(await page.$eval('.route-target.unresolved select',n=>n.getBoundingClientRect().height>0 && !n.disabled),true,'Unknown targets can be chosen in the destination field')
  assert.match(await page.$eval('.change-tag',n=>n.textContent),/请选择目标页面/)
  await page.select('select[aria-label="跳转目标 首页 · 我的"]','2')
  assert.equal(await page.$eval('.actions .el-button--primary',n=>n.disabled),true)
  await page.$$eval('.actions button',nodes=>nodes.find(n=>n.textContent.includes('检查新目标')).click())
  await page.waitForFunction(()=>window.navTest.requests.length===2)
  assert.equal(await page.evaluate(()=>window.navTest.requests.at(-1).navigationResolutions[0].targetPageId),2)
  await page.waitForFunction(()=>!document.querySelector('.route-target.unresolved'))
  assert.equal(await page.$eval('article.item input[type=checkbox]',n=>n.checked),false,'Resolved target still requires review')
  assert.equal(await page.$eval('article.item input[type=checkbox]',n=>n.disabled),false,'Resolved target can be selected for application')
  await page.evaluate(()=>window.navTest.ordinaryUnresolvedReview())
  await page.waitForSelector('.route-target.unresolved select')
  await page.select('select[aria-label="跳转目标 首页 · 我的"]','2')
  assert.equal(await page.$eval('.actions .el-button--primary',n=>n.disabled),true,'Ordinary target also requires checking')
  await page.$$eval('.actions button',nodes=>nodes.find(n=>n.textContent.includes('检查新目标')).click())
  await page.waitForFunction(()=>window.navTest.requests.length===3)
  assert.deepEqual(await page.evaluate(()=>window.navTest.requests.at(-1).targetResolutions),[{stableKey:'1:ordinary',targetPageId:2}])
  assert.deepEqual(await page.evaluate(()=>window.navTest.requests.at(-1).navigationResolutions),[])
  await page.waitForFunction(()=>!document.querySelector('.route-target.unresolved'))
  assert.equal(await page.$eval('article.item input[type=checkbox]',n=>n.disabled || n.checked),false)
  await (await page.$('article.item input[type=checkbox]')).click()
  await page.click('.actions .el-button--primary')
  assert.deepEqual(await page.evaluate(()=>window.navTest.applied.at(-1).selectedIds),['ordinary'])
  await page.select('select[aria-label="跳转目标 首页 · 我的"]','3')
  await page.click('article.item .item-more > summary')
  await page.select('select[aria-label="下次还推荐吗 首页 · 我的"]','element')
  assert.equal(await page.$eval('.actions .el-button--primary',n=>n.disabled),false,'Stopping recommendations clears the pending target instead of blocking application')
  await page.click('.actions .el-button--primary')
  assert.deepEqual(await page.evaluate(()=>window.navTest.applied.at(-1).exclusions),[{itemId:'ordinary',scope:'element'}])
  await page.evaluate(()=>window.navTest.conflictReview())
  await page.waitForSelector('.confirmation-hint')
  assert.equal(await page.$('article.item .route-target select'),null,'Conflicts cannot be overwritten by a target selection')
  assert.match(await page.$eval('.confirmation-hint',n=>n.textContent),/冲突.*画布/)
  await page.evaluate(()=>window.navTest.sampleReview())
  await page.waitForFunction(()=>document.querySelectorAll('article.item').length===2)
  await (await page.$('article.item input[type=checkbox]')).click()
  await page.setViewport({width:1400,height:1100})
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.autowire-dialog')).opacity==='1' && !document.querySelector('.dialog-fade-enter-active'))
  await (await page.$('.autowire-dialog')).screenshot({path:fileURLToPath(new URL('../../autowire-review-clarity.png',import.meta.url))})
  assert.deepEqual(errors,[])
  console.log('PASS: iframe navigation; visible destination selectors; navigation and ordinary target recheck; conflict protection; review memory; exclusion scopes; no API writes.')
} finally {await browser.close()}
